# SPDX-FileCopyrightText: 2019 John Irle
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "public/*"
SPDX-FileCopyrightText = "2019 Your Name"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "*.json"
SPDX-FileCopyrightText = "2019 John Irle"
SPDX-License-Identifier = "MIT"
